beyond-sw-camp/be12-fin-5verdose-WMTHIS-FE

src/components/inventory/Inventory.vue

[Feat] My제고목록페이지 생성

---

src/components/inventory/Inventory.vue

[Feat] 재고관리페이지생성

---

src/components/InventoryManagement.vue

[Feat] 재고관리페이지

---

src/components/POSMain.vue
src/components/POSMenu.vue
src/components/POSPay.vue

[feat] POS 테이블 기능 구현

---

src/components/InventoryModifyModal.vue

[Feat] 재고수정모달창 추가

---

src/components/MarketPostList.vue
src/components/MenuRegisterModal.vue
src/components/POSMenu.vue
src/components/POSPay.vue
src/components/TradeList.vue
src/components/TradeRequestModal.vue

[feat] 거래 내역 페이지 추가 (#48, #50)

---

src/components/InventoryManagement.vue
src/components/InventorySaleModal.vue

재고 판매 모달창 추가

---

src/components/InventoryManagement.vue
src/components/InventoryParticularModal.vue

[Feat]재고상세모달창 추가

---

src/components/Calendar.vue
src/components/MyMenu.vue
src/components/SalesAnalysisDetail.vue
src/components/SalesDetail.vue

[feat] 매출 상세 분석 대시 보드 추가(#51)

---

src/components/InventoryCorrectionModal.vue
src/components/InventoryParticularModal.vue

[Feat]상세모달페이지에서보정모달창 추가가

---

README.md

[feat] readme figma 링크 수정

---

src/components/Inventory.vue
src/components/InventoryModifyModal.vue
src/components/InventoryRegisterModal.vue
src/components/InventoryStoreModal.vue

[Feat] 재고 변수, 함수 변경

---

src/components/InventoryCorrectionModal.vue
src/components/InventoryManagement.vue
src/components/InventoryModifyModal.vue
src/components/InventoryParticularModal.vue
src/components/InventoryRegisterModal.vue
src/components/InventorySaleModal.vue
src/components/InventoryStoreModal.vue

[Feat]재고관리 페이지 수정완

---

src/components/inventory_management/InventoryManagement.vue

[Fix] 재고관리 css수정정

---

src/components/inventory_management/InventoryManagement.vue

[Fix] 재고관리 css수정

---

src/components/inventory_management/InventoryManagement.vue

[Feat] 재고관리페이지 선추가

---

src/components/inventory_management/InventoryRegisterModal.vue
src/stores/useInventoryStore.js

[Feat] 재고 store.js  추가가

---

src/components/inventory_management/InventoryRegisterModal.vue
src/stores/useInventoryStore.js

[Feat] 재고관리등록추가가

---

src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryManagement.vue
src/components/inventory_management/InventoryParticularModal.vue
src/components/inventory_management/InventoryStoreModal.vue

재고 상세페이지 모달창 수정 및 상세페이지 정보 불러오기 추가

[Feat] 재고 상세페이지 수정및 추가

---

src/components/inventory_management/Inventory.vue
src/components/inventory_management/InventoryModifyModal.vue

[Feat]재고수정할때 정보

---

src/components/inventory_management/Inventory.vue
src/components/inventory_management/InventoryManagement.vue
src/components/inventory_management/InventoryModifyModal.vue
src/stores/useInventoryStore.js

[Feat]재고수정 및 등록 수정

---

src/components/inventory_management/InventoryManagement.vue
src/components/inventory_management/InventoryParticularModal.vue
src/components/inventory_management/InventoryRegisterModal.vue
src/components/inventory_management/InventoryStoreModal.vue
src/stores/useInventoryStore.js

[Feat]재고정보 불러오기

---

src/components/inventory_management/InventoryRegisterModal.vue
src/stores/useInventoryStore.js

[Feat] 재고등록 최종수정

---

src/api/MenuApi.js
src/components/inventory_management/Inventory.vue
src/stores/useInventoryStore.js

[Feat] 재고 목록 불러오기

---

src/components/inventory_management/Inventory.vue
src/components/inventory_management/InventoryManagement.vue
src/components/inventory_management/InventoryParticularModal.vue
src/components/inventory_management/InventoryRegisterModal.vue
src/components/inventory_management/InventoryStoreModal.vue

[Feat] 재고 수정

---

src/api/MenuApi.js
src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryModifyModal.vue

[Feat] 재고수정모달창 최소수량 추가

---

src/components/inventory_management/Inventory.vue
src/components/inventory_management/InventoryRegisterModal.vue

[Feat] 재고관리 등록 최종수정

---

src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryParticularModal.vue

재고보정모달창에서 수정한 후 재고 상세모달창에서 자동으로 업데이트 수정

[Fix] 재고보정모달창에서 수정한 후 업데이트 수정정

---

src/components/inventory_management/InventoryManagement.vue
src/components/inventory_management/InventoryParticularModal.vue

[Fix] 전체 재고 총수량 새로고침 없이 업데이트 수정정

---

src/api/MenuApi.js
src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryParticularModal.vue

재고입고 내역 삭제 추가 

---

src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryModifyModal.vue
src/components/inventory_management/InventoryRegisterModal.vue
src/components/inventory_management/InventoryStoreModal.vue

[Feat] 재고 등록 중복요청 방지

---

src/components/inventory_management/InventoryCorrectionModal.vue
src/components/inventory_management/InventoryModifyModal.vue
src/components/inventory_management/InventoryParticularModal.vue
src/components/inventory_management/InventoryRegisterModal.vue
src/components/inventory_management/InventorySaleModal.vue
src/components/inventory_management/InventoryStoreModal.vue

[Fix]모달 창 수정

---

src/components/inventory_management/InventorySaleModal.vue

[Fix] 재고판매 중복 등록 수정

---

src/components/inventory_management/InventorySaleModal.vue

[Fix] 재고판매 등록 중복방지

---

src/components/inventory_management/Inventory.vue
src/components/inventory_management/InventoryManagement.vue
src/components/menu_management/category/MyCategory.vue
src/components/menu_management/menu/MyMenu.vue
src/components/menu_management/option/MyOption.vue

[Feat] 재고 목록 불러오기 기능
